version: '3.9'
services:
    nango-db:
        image: postgres
        container_name: nango-db
        environment:
            POSTGRES_PASSWORD: nango
            POSTGRES_USER: nango
            POSTGRES_DB: nango
        ports:
            - '5432:5432'
        networks:
            - nango

    redis:
        image: redis
        container_name: redis
        volumes:
            - ./redis-data:/data
        ports:
            - '6379:6379'
        networks:
            - nango

    nango-server:
        image: nangohq/nango-server
        container_name: nango-server
        restart: always
        env_file:
            - .env
        ports:
            - '80:3003'
        depends_on:
            - nango-db
        networks:
            - nango

networks:
    nango:
