version: '3.9'
services:
    nango-db:
        image: postgres:15.5-alpine
        container_name: nango-db
        environment:
            POSTGRES_PASSWORD: nango
            POSTGRES_USER: nango
            POSTGRES_DB: nango
        ports:
            - '${NANGO_DB_PORT:-5432}:5432'
        volumes:
            - ./nango-data:/var/lib/postgresql/data
        networks:
            - nango

    temporal:
        image: temporalio/auto-setup
        container_name: temporal
        depends_on:
            - nango-db
        environment:
            - DB=postgresql
            - DB_PORT=5432
            - POSTGRES_USER=nango
            - POSTGRES_PWD=nango
            - POSTGRES_SEEDS=nango-db
        ports:
            - 7233:7233
        networks:
            - nango

    nango-redis:
        image: redis:7.2.4
        container_name: nango-redis
        ports:
            - '6379:6379'
        networks:
            - nango

    es:
        container_name: es
        image: elasticsearch:8.12.2
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9500:9200
            - 9600:9300
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        networks:
            - nango
        deploy:
            resources:
                limits:
                    memory: 2GB

networks:
    nango:

volumes:
    esdata1:
        driver: local
