name: "[Release] Build service images"
on:
    push:
        branches:
            - master
            - staging/**
    pull_request:

concurrency:
    group: pulls/${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    nango-persist:
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: persist
            run-cmd: ts-build
            tags: -t nangohq/nango-persist:${{ github.event.pull_request.head.sha }} ${{ github.ref == 'refs/heads/master' && '-t nangohq/nango-persist:enterprise-${{ github.event.pull_request.head.sha }} -t nangohq/nango-persist:enterprise -t nangohq/nango-persist:hosted-${{ github.event.pull_request.head.sha }} -t nangohq/nango-persist:hosted' || '' }}
    nango-jobs:
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: jobs
            run-cmd: ts-build
            tags: -t nangohq/nango-jobs:${{ github.event.pull_request.head.sha }} ${{ github.ref == 'refs/heads/master' && '-t nangohq/nango-jobs:enterprise-${{ github.event.pull_request.head.sha }} -t nangohq/nango-jobs:enterprise -t nangohq/nango-jobs:hosted-${{ github.event.pull_request.head.sha }} -t nangohq/nango-jobs:hosted' || '' }}
    nango-runner:
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: runner
            run-cmd: ts-build
            tags: -t nangohq/nango-runner:${{ github.event.pull_request.head.sha }} -t nangohq/nango-runner:enterprise-${{ github.event.pull_request.head.sha }} -t nangohq/nango-runner:enterprise -t nangohq/nango-runner:hosted-${{ github.event.pull_request.head.sha }} -t nangohq/nango-runner:hosted
    nango-server-staging:
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: server
            run-cmd: build:staging
            tags: -t nangohq/nango-server:staging-${{ github.event.pull_request.head.sha }}

    nango-server-prod:
        if: github.ref == 'refs/heads/master'
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: server
            run-cmd: build:prod
            tags: -t nangohq/nango-server:production-${{ github.event.pull_request.head.sha }}
    nango-server-self-hosted:
        if: github.ref == 'refs/heads/master'
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: server
            run-cmd: build:hosted
            tags: -t nangohq/nango-server:hosted -t nangohq/nango-server:hosted-${{ github.event.pull_request.head.sha }}
    nango-server-enterprise:
        if: github.ref == 'refs/heads/master'
        uses: ./.github/workflows/push-container.yaml
        secrets: inherit
        with:
            package: server
            run-cmd: build:enterprise
            tags: -t nangohq/nango-server:enterprise -t nangohq/nango-server:enterprise-${{ github.event.pull_request.head.sha }}
