name: Build unified Docker image

on:
  push:
    branches:
      - master
      - staging/**
  pull_request:


jobs:
  build-image:
    strategy:
      matrix:
        group:
          - name: 'staging'
            if: github.ref == 'refs/heads/master'
          - name: 'prod'
            if: github.ref == 'refs/heads/master'
          - name: 'enterprise'
            if: github.ref == 'refs/heads/master'

    secrets: inherit
    uses: ./.github/workflows/build-image-reusable.yml
    with:
      if: ${{ matrix.group.if }}
      name: ${{ matrix.group.foo }}

