name: Build unified Docker image

on:
  push:
    branches:
      - master
      - staging/**
  pull_request:

jobs:
  push-container:
    runs-on: ubuntu-latest
    env:
      CAN_PUSH: '${{ secrets.DOCKER_PASSWORD != '' && secrets.DOCKER_USERNAME != '' }}'
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: env.CAN_PUSH == 'true'
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build image
        run: |
          ./scripts/build_docker.sh staging ${{ github.event.pull_request.head.sha || github.sha }}
