name: '[Release] Build unified Docker image'

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:
    merge_group:

jobs:
    build-image:
        # strategy:
        #     matrix:
        #         group:
        #             # Commented for now
        #             # - name: 'enterprise'
        #             #   if: ${{ github.ref == 'refs/heads/master' }}

        secrets: inherit
        uses: ./.github/workflows/build-image-reusable.yaml
        with:
            if: ${{ matrix.group.if }}
            name: ${{ matrix.group.name }}
