name: CLI Publish & Verify

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:

concurrency:
    group: verify-cli-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    publish-and-test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@nangohq'
                  always-auth: true
            - run: npm run build:hosted
            - name: Publish the shared package
              working-directory: packages/shared
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  GIT_HASH=$(git rev-parse HEAD)
                  npm run build
                  npm version 0.0.1-$GIT_HASH --workspaces-update=false
                  npm publish --ignore-scripts
            - name: Publish the cli
              working-directory: packages/cli
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  GIT_HASH=$(git rev-parse HEAD)
                  npm install @nangohq/shared@0.0.1-$GIT_HASH
                  npm run build
                  npm version 0.0.1-$GIT_HASH --workspaces-update=false
                  npm publish --ignore-scripts
            - name: Install the cli from the github package registry
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  GIT_HASH=$(git rev-parse HEAD)
                  npm install nango@0.0.1-$GIT_HASH
                  npx nango version --debug
