name: Docs Update

on:
    push:
        branches:
            - master
        paths:
            - packages/shared/flows.yaml
            - docs-v2/integrations/all/*.md
    pull_request:
        paths:
            - packages/shared/flows.yaml
            - docs-v2/integrations/all/*.md

jobs:
    update-docs-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - name: Install dependencies
              run: npm ci

            - run: npm run docs:generate

            - uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  ref: ${{ github.event.pull_request.head.ref }}
