name: Nango Integration Flows Compile

on: [push, pull_request]

concurrency:
    group: flows-compile--${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    flow-compilation:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install nango CLI
              run: |
                # compile, install CLI and verify it can run
                npm run i
                npm run ts-build
                npm install -g ./packages/cli
                nango version

            - name: Compile with Nango
              run: |
                set -e
                cd integration-templates
                for dir in */; do
                  if [[ "$dir" != "." && "$dir" != "integration-templates/" ]]; then
                      cd "$dir"
                      mkdir -p nango-integrations
                      find . -maxdepth 1 ! -name '.' ! -name 'nango-integrations' -exec mv -t nango-integrations {} +
                      cd nango-integrations
                      output=$(nango compile 2>&1)
                      echo "$output"
                      if [[ "$output" == *"Error compiling"* ]]; then
                        echo "Error found in directory $dir"
                        exit 1
                      fi
                      cd ../../
                  fi
                done
