name: '[Release] NPM publish'

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:

jobs:
    npm-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_PAT }}

            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'
                  registry-url: 'https://registry.npmjs.org'

            # - name: Publish npm packages
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            #   shell: bash
            #   run: |
            #       bash ./scripts/publish.sh ${{ inputs.version }}

            - name: Publish release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm ci
                  npx zx ./scripts/gitrelease.mjs ${{ inputs.version }} ${{ github.head_ref || github.ref_name }}
