name: Push container

on:
    workflow_call:
        inputs:
            package:
                required: true
                type: string
            run-cmd:
                required: true
                type: string
            tags:
                required: true
                type: string

jobs:
    push-container:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-buildx-action@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            - uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push container
              run: |
                npm run i
                npm run ${{ inputs.run-cmd }}
                node scripts/flows.js
                docker buildx build -f packages/${{ inputs.package }}/Dockerfile --platform linux/amd64 ${{ inputs.tags }} . --no-cache --output type=registry

