name: Run Unit & Integration Tests

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:
    merge_group:

concurrency:
    group: tests-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - run: npm ci
            - run: npm run ts-build
            - run: npm run test:unit -- --exclude packages/cli/

            - run: docker pull elasticsearch:8.13.0
            - run: docker pull postgres:15.5-alpine
            - run: npm run test:integration
