name: Run Unit & Integration Tests

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:
    merge_group:

concurrency:
    group: tests-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15.5-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: nango_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 2s
                    --health-timeout 2s
                    --health-retries 5

            elasticsearch:
                image: elasticsearch:8.13.0
                env:
                    discovery.type: single-node
                    xpack.security.enabled: false
                options: >-
                    --health-cmd "curl http://localhost:9200/_cluster/health"
                    --health-interval 2s
                    --health-timeout 2s
                    --health-retries 5
                ports:
                    - 9200:9200

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - run: npm ci
            - run: npm run ts-build
            - run: npm run test:unit -- --exclude packages/cli/

            - run: npm run test:integration
              env:
                  NANGO_DB_PASSWORD: postgres
                  NANGO_DB_HOST: localhost
                  NANGO_DB_USER: postgres
                  NANGO_DB_PORT: 5432
                  NANGO_DB_NAME: nango_test
                  TELEMETRY: false
                  RECORDS_DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/nango_test'
                  NANGO_LOGS_ES_URL: 'http://localhost:9200'
                  NANGO_LOGS_ES_USER: ''
                  NANGO_LOGS_ES_PWD: ''
                  NANGO_LOGS_ENABLED: true
