name: Run Unit & Integration Tests

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:

concurrency:
    group: tests-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: '0'

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version: ${{ matrix.node-version }}
            - run: npm run build:hosted
            - run: npm run test:unit
            - run: npm run test:integration

            - name: Make sure flows.yaml is compiled
              run: |
                  node ./scripts/flows.js

                  REPO_DIRTY=$(git status --short)
                  if [[ ! -z "$REPO_DIRTY" ]]; then
                    git diff
                    echo ""
                    echo -e "\r⛔️ flows.yaml hasn't been compiled, please run:"
                    echo -e "node ./scripts/flows.js"
                    exit 1
                  fi
