name: Run Unit & Integration Tests

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:
    merge_group:

concurrency:
    group: tests-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15.5-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: nango_test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 2s
                    --health-timeout 2s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - run: npm ci
            - run: npm run ts-build
            - run: npm run test:unit -- --exclude packages/cli/
            - run: npm run test:integration
