name: Yaml Validation

on: [push]

concurrency:
  group: validation-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint providers file
        uses: ibiqlik/action-yamllint@v3

      - name: Lint Docker Compose Files
        uses: ibiqlik/action-yamllint@v3
