name: Webflow Sync

on:
    push:
        branches:
            - master
            - alan/webflow-sync-action
        paths:
            - packages/shared/providers.yaml
            - docs-v2/integrations/all/*.md

jobs:
    webflow-sync-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - name: Install dependencies
              run: npm ci

            - run: npx tsx scripts/webflow-api-sync.ts
