version: '3.9'
services:
    nango-db:
        image: postgres
        container_name: nango-db
        environment:
            POSTGRES_PASSWORD: nango
            POSTGRES_USER: nango
            POSTGRES_DB: nango
        ports:
            - '${NANGO_DB_PORT:-5432}:5432'
        volumes:
            - ./nango-data:/var/lib/postgresql/data
        networks:
            - nango

    nango-server:
        image: nangohq/nango-server
        container_name: nango-server
        environment:
            - TEMPORAL_ADDRESS=temporal:7233
        restart: always
        ports:
            - '3003:3003'
        depends_on:
            - nango-db
        networks:
            - nango

    nango-sync-server:
        image: nangohq/sync-worker:0.17.71-rc
        container_name: nango-sync-server
        restart: always
        ports:
            - '3004:3004'
        environment:
            - TEMPORAL_ADDRESS=temporal:7233
        depends_on:
            - nango-db
            - temporal
        volumes:
            - "./nango-integrations:/usr/nango-sync-server/src/packages/shared/dist/lib/nango-integrations"
        networks:
            - nango

    temporal:
        image: temporalio/auto-setup
        container_name: temporal
        depends_on:
            - nango-db
        environment:
            - DB=postgresql
            - DB_PORT=5432
            - POSTGRES_USER=nango
            - POSTGRES_PWD=nango
            - POSTGRES_SEEDS=nango-db
            - LOG_LEVEL=error
        ports:
            - 7233:7233
        networks:
            - nango

networks:
    nango:
